import { beforeAll, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

vi.hoisted(() => {
  // src/mcp/server.ts wires OAuth from isDevBypass(): development + flag
  // omits the provider entirely (no bearer middleware), so the real
  // singleton can be imported in-process without Supabase env vars or
  // tokens. Same seeding as route.test.ts (mirrors what
  // scripts/mcp-dev.ts sets). Must run before the dynamic route imports
  // below (the singleton is constructed at import time).
  // `as Record<...>` — lib.dom/next-env types NODE_ENV as readonly.
  (process.env as Record<string, string>).NODE_ENV = "development";
  (process.env as Record<string, string>).MCP_DEV_BYPASS = "true";
});

// Construction-time determinism: the route module builds its dedicated
// server instance at import, resolving isDevBypass() THEN (fail-closed is
// per-construction by design — Vercel env is fixed at boot, so prod is
// deterministic). Under full-suite CPU contention the ~4s cold import can
// straddle into a later test's stubEnv window, constructing with the wrong
// env. Import once here (generous budget) so every test below reuses the
// bypass-built instance; per-test stubEnv then only affects REQUEST-time
// auth (buildToolContext), which is exactly the split the fail-closed test
// pins: OAuth-mounted server + unauthenticated request → Unauthorized
// envelope (never a throw, never a 500).
beforeAll(async () => {
  vi.stubEnv("MCP_DEV_BYPASS", "true");
  await import("./route");
}, 30_000);

// Embedded route contract: the Next handler serves the MCP protocol
// without the standalone CLI. Dev bypass resolves the seeded user
// (test_hash_pwd@smu.edu.sg); never active in production.
describe("embedded /api/mcp", () => {
  it("tools/list returns the 50-tool catalog", async () => {
    vi.stubEnv("MCP_DEV_BYPASS", "true");
    const route = await import("./route");
    const res = await route.POST(
      new Request("http://localhost/api/mcp", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json, text/event-stream",
        },
        body: JSON.stringify({
          jsonrpc: "2.0",
          id: 1,
          method: "tools/list",
          params: {},
        }),
      }),
    );
    expect(res.status).toBe(200);
    // mcp-use@2.3.4 answers JSON-RPC over SSE (`text/event-stream`):
    // `event: message\ndata: {...}\n\n` frames, even when the client sends
    // `Accept: application/json, text/event-stream` (stateless POST returns
    // a stream with one frame). Parse the `data:` frame like
    // src/mcp/serialization.test.ts does — same real wire shape, not a mock.
    const text = await res.text();
    let payload: unknown;
    try {
      payload = JSON.parse(text) as unknown;
    } catch {
      const dataLine = text.split("\n").find((l) => l.startsWith("data:"));
      expect(dataLine, `no data frame in SSE body:\n${text}`).toBeDefined();
      payload = JSON.parse(dataLine!.slice("data:".length).trim()) as unknown;
    }
    const body = payload as {
      result?: { tools?: Array<{ name: string }> };
    };
    expect(body.result?.tools).toHaveLength(50);
    vi.unstubAllEnvs();
  }, 30_000);

  it("fail-closed without bypass or token", async () => {
    vi.stubEnv("MCP_DEV_BYPASS", "");
    const route = await import("./route");
    const res = await route.POST(
      new Request("http://localhost/api/mcp", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json, text/event-stream",
        },
        body: JSON.stringify({
          jsonrpc: "2.0",
          id: 2,
          method: "tools/call",
          params: { name: "search-courses", arguments: { query: "IS" } },
        }),
      }),
    );
    expect(res.status).not.toBe(500);
    const text = await res.text();
    expect(text).toMatch(/Unauthorized|disabled|error/i);
    vi.unstubAllEnvs();
  });
});

// View manifest precondition (.mcp-use/build/manifest.json, gitignored):
// generated by `bunx mcp-use build --mcp-dir src/mcp --views-dir views`
// (or `withMcpUse` at next-config eval — `bun run dev` / `bun run build`).
// Without it `createNextHandler` throws ENOENT on first request instead of
// serving views. Regenerate after changing views/ or src/mcp/view-tools/.

type ToolDef = { _meta?: unknown; [k: string]: unknown };

function isViewMeta(m: unknown): m is { ui: { resourceUri: string } } {
  if (typeof m !== "object" || m === null || !("ui" in m)) return false;
  const { ui } = m;
  return (
    typeof ui === "object" &&
    ui !== null &&
    typeof (ui as { resourceUri: unknown }).resourceUri === "string"
  );
}

function parseRpcBody(text: string): unknown {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    // mcp-use@2.3.4 answers JSON-RPC over SSE (`text/event-stream`):
    // `event: message\ndata: {...}\n\n` frames (same helper shape as the
    // tools/list test above — kept separate: that one is the verbatim
    // Task 4 pin, this one returns the payload for reuse below).
    const dataLine = text.split("\n").find((l) => l.startsWith("data:"));
    if (dataLine === undefined)
      throw new Error(`no data frame in SSE body:\n${text}`);
    return JSON.parse(dataLine.slice("data:".length).trim()) as unknown;
  }
}

async function postRpc(method: string, params: unknown, id: number) {
  const route = await import("./route");
  const res = await route.POST(
    new Request("http://localhost/api/mcp", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "application/json, text/event-stream",
      },
      body: JSON.stringify({ jsonrpc: "2.0", id, method, params }),
    }),
  );
  expect(res.status).toBe(200);
  return { route, payload: parseRpcBody(await res.text()) };
}

describe("embedded /api/mcp views", () => {
  it("every view URI from tool metadata loads HTML", async () => {
    // beforeAll already imported ./route (bypass-built instance); stub here
    // only affects request-time auth, and the cached import returns instantly.
    vi.stubEnv("MCP_DEV_BYPASS", "true");
    const { route, payload } = await postRpc("tools/list", {}, 3);
    const tools =
      (payload as { result?: { tools?: ToolDef[] } }).result?.tools ?? [];
    expect(tools.length).toBe(50);
    // KEY-PATH CALIBRATION (mcp-use@2.3.4, verified against the live
    // tools/list response): the brief's `_mcp-use`-substring sketch does
    // not match — view-bound tools carry
    // `_meta: { "ui/resourceUri": "ui://views/<name>.html",
    //           ui: { resourceUri: "ui://views/<name>.html" } }`
    // (see `buildToolUiMeta` in mcp-use/dist/index.js:
    // `UI_RESOURCE_URI_META_KEY = "ui/resourceUri"`,
    // `viewResourceUri = "ui://views/${name}.html"`). Read the canonical
    // `ui.resourceUri` object path; assert the flat key agrees so a
    // half-written annotation cannot slip through.
    const bound = tools.filter((t) => isViewMeta(t._meta));
    const viewUris = bound.map(
      (t) => (t._meta as { ui: { resourceUri: string } }).ui.resourceUri,
    );
    expect(viewUris).toHaveLength(7);
    expect([...viewUris].sort()).toEqual([
      "ui://views/bid-explorer.html",
      "ui://views/bid-plan.html",
      "ui://views/calendar-links.html",
      "ui://views/course-search.html",
      "ui://views/review-cards.html",
      "ui://views/roadmap-view.html",
      "ui://views/timetable.html",
    ]);
    for (const t of bound) {
      const meta = t._meta as {
        ui: { resourceUri: string };
        [k: string]: unknown;
      };
      expect(
        meta["ui/resourceUri"],
        `flat ui/resourceUri disagrees for ${meta.ui.resourceUri}`,
      ).toBe(meta.ui.resourceUri);
    }
    // Views are MCP resources, not HTTP paths: the `ui://` URI has no
    // pathname to GET (that sketch 404s by design — `createMcpMount`
    // answers ONLY the exact basePath, and the catch-all forwards
    // non-basePath GETs to the SDK handlers). Read each view through
    // `resources/read` (same RPC transport as tools/list) and assert the
    // synthesized document: doctype + view root + the entry script the
    // manifest primed for that view.
    for (const uri of viewUris) {
      const viewName = uri.slice("ui://views/".length, -".html".length);
      const { payload: readPayload } = await postRpc(
        "resources/read",
        { uri },
        4,
      );
      const contents = (
        readPayload as {
          result?: {
            contents?: Array<{
              uri?: unknown;
              mimeType?: unknown;
              text?: unknown;
            }>;
          };
        }
      ).result?.contents;
      expect(contents, `empty resources/read for ${uri}`).toHaveLength(1);
      const content = contents![0]!;
      expect(content.uri).toBe(uri);
      expect(content.mimeType).toBe("text/html;profile=mcp-app");
      expect(typeof content.text).toBe("string");
      const html = content.text as string;
      expect(html).toContain("<!doctype html>");
      expect(html).toContain('id="root"');
      // Every same-origin script/link ref in the document must GET 200
      // through the catch-all (the JS/CSS the brief requires): refs are
      // absolute URLs synthesized from the request origin + basePath +
      // `_mcp-use/views/<name>/…` (see `synthesizeViewDocument` +
      // `createViewAssetsHandler` in mcp-use/dist/index.js).
      const refs = [
        ...html.matchAll(/<(?:script|link)[^>]+(?:src|href)="([^"]+)"/g),
      ].map((m) => m[1]!);
      expect(refs.length, `no asset refs in ${uri} document`).toBeGreaterThan(
        0,
      );
      for (const ref of refs) {
        const url = new URL(ref);
        expect(url.origin, `cross-origin asset ref ${ref} in ${uri}`).toBe(
          "http://localhost",
        );
        const res = await route.GET(new Request(ref));
        expect(res.status, `asset GET ${url.pathname}`).toBe(200);
        expect(
          (await res.arrayBuffer()).byteLength,
          `empty asset body ${url.pathname}`,
        ).toBeGreaterThan(0);
      }
      expect(
        refs.some((r) => r.includes(`/views/${viewName}/`)),
        `no view-scoped asset ref for ${viewName}: ${refs.join(", ")}`,
      ).toBe(true);
    }
    vi.unstubAllEnvs();
    // ~15 RPCs + asset GETs; generous budget for full-suite contention.
  }, 60_000);
});
