name: Unit Tests

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "package.json"
      - "bun.lock"
      - "vitest.config.ts"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "src/**"
      - "package.json"
      - "bun.lock"
      - "vitest.config.ts"

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - run: bun install

      - name: Run unit tests
        run: bun run test
